// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plwhyfpgqdapixpqniiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsd2h5ZnBncWRhcGl4cHFuaWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjcwNzksImV4cCI6MjA3MDI0MzA3OX0.xdN-ODcAVEHcH-eRjqtm_ztxNY8y4WrWR5YPQahUmN4  ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});